# vae
vae_path: './pretrained_models/sd-vae-ft-mse/'

# unet
unet_config_file: 'config/unet.json'
unet_resume_file: 'checkpoints/paper_without_depth/1_90000/unet/diffusion_pytorch_model.safetensors'

# checkpoint
checkpoint_dir: './checkpoints/paper_without_depth_s2'
checkpoint_save_interval: 5000
console_log_interval: 2
checkpoint_valiation_interval: 5000

# dataset
dataset:
  root_dir: '/export/App/training_platform/PinoModel/cbfs/wql/digit-swin/Data_depth_v2'
  train_file : '/export/App/training_platform/PinoModel/cbfs/wql/digit-swin/Data_depth_v2/paper_list/3d_train.txt'
  val_file: '/export/App/training_platform/PinoModel/cbfs/wql/digit-swin/Data_depth_v2/paper_list/3d_val_3.txt'
  img_size: 256
  batch_size: 16
  num_workers: 20

# optimizer
opti:
  gradient_accumulation_steps: 1
  warmup_steps: 0
  max_steps: 200000
  use_ema: false

  # lr
  lr: 1.0e-5
  min_lr: 0.5e-5
